### PR TITLE
Fix problem with error display

### PR DESCRIPTION
**Pull request by april**

### CODE REVIEW

**Comment by april** [comment]
Merging myself, since it's an approved change from the CLI.

**Comment by gene1wood** [comment]
This broke display of all errors as they weren't updated to use the new data structure of 

```
{
  "error": {
    "message": "message here"
  }
}
```

Result is that error messages now display as `Error: undefined`

This would have needed to be [updated here as well](https://github.com/mozilla-iam/federated-aws-rp/blob/cdc10923fcec4efa91edfd6f6caeb9519ad177b1/functions/federated_aws_rp/app.py#L154)

**Comment by april** [comment]
Was this only broken in the federated RP?

**Comment by gene1wood** [comment]
Yes, because the related backend change to match this frontend change was done in mozilla-iam/mozilla-aws-cli#203

I've submitted PR #25 that fixes this in federated AWS RP

**Pull request merged**
